modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="[47,)" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "cataclysm"

# The version number of the mod
version = "2.63" #mandatory

# A display name for the mod
displayName = "cataclysm" #mandatory
credits="0dyss2y,HedwigOwls,danimodder,Gibb50,poogy" #optional
authors="L_Ender" #optional
description='''
Hello
Also Listen Cataclysmic Tunes
https://www.curseforge.com/minecraft/texture-packs/cataclysmic-tunes
Artist=dogulkkun,mango03034,Gytator,LegendNoob
Patron
[Adam,
Angry Mutant Enderman,
darkMind204,
DENOBODY2,
Hippo0824,
printa,
walker,
참치,
3T,
danimodder,
EternalOne,
Karat Feng,
lucy,
nameed,
PeopleMcNugget,
qwerqweqq,
Svmf2023,
Th3P3dr3nder99]
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cataclysm]] #optional
# the modid of the dependency
modId="lionfishapi" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[2.4,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.cataclysm]]
modId="forge"
mandatory=true
versionRange="[36.0.42,)"
ordering="NONE"
side="BOTH"

