modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId= "cataclysm" #mandatory
version="2.00" #mandatory
# A display name for the mod
displayName="Cataclysm Mod" #mandatory
credits="0dyss2y,HedwigOwls,gytator,danimodder,Gibb50" #optional
authors="L_Ender" #optional
description='''
Hello
Also Listen Cataclysmic Tunes
https://www.curseforge.com/minecraft/texture-packs/cataclysmic-tunes
Artist=dogulkkun,mango03034
Patron
[Adam,
Angry Mutant Enderman,
darkMind204,
DENOBODY2,
Hippo0824,
printa,
walker,
참치,
3T,
danimodder,
EternalOne,
Karat Feng,
lucy,
nameed,
PeopleMcNugget,
qwerqweqq,
Svmf2023,
Th3P3dr3nder99]
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cataclysm]] #optional
# the modid of the dependency
modId="lionfishapi" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[1.9,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.cataclysm]]
modId="forge"
mandatory=true
versionRange="[36.0.42,)"
ordering="NONE"
side="BOTH"
